import Foundation

/// The pf ruleset Hector loads.
///
/// macOS' stock `/etc/pf.conf` already evaluates `anchor "com.apple/*"`, so loading our rules into a
/// sub-anchor of it activates them without editing `/etc/pf.conf`, and flushing the anchor removes
/// them completely.
public enum PFAnchor {
    public static let name = "com.apple/250.Netbite"
    public static let blockTable = "netbite_block"
    public static let geoTable = "netbite_geo"

    /// pf rules referencing the two table files in `tableDirectory`.
    ///
    /// `block return` answers with a TCP reset or ICMP unreachable, so apps fail at once instead of
    /// waiting for a timeout.
    public static func ruleset(tableDirectory: String) -> String {
        """
        # Generated by Hector. Do not edit: it is rewritten on every apply.
        # Loaded with: pfctl -a "\(name)" -f <this file>
        table <\(blockTable)> persist file "\(tableDirectory)/\(blockTable).table"
        table <\(geoTable)> persist file "\(tableDirectory)/\(geoTable).table"
        block return out quick to <\(blockTable)>
        block return out quick to <\(geoTable)>
        block drop in quick from <\(geoTable)>

        """
    }

    /// One network per line, the format `pfctl -T replace -f` and `table … file` read.
    public static func tableFile(_ networks: [CIDR]) -> String {
        networks.map(\.description).joined(separator: "\n") + (networks.isEmpty ? "" : "\n")
    }

    /// The commands the privileged helper runs to apply a ruleset (pf is reference-counted with -E).
    public static func applyCommands(rulesetPath: String) -> [[String]] {
        [
            ["/sbin/pfctl", "-a", name, "-f", rulesetPath],
            ["/sbin/pfctl", "-E"],
        ]
    }

    /// The command that removes every Netbite pf rule.
    public static let flushCommand = ["/sbin/pfctl", "-a", name, "-F", "all"]
}
